import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/layoutComponents/Footer";
import Header from "@/components/layoutComponents/Header";
import { LanguageContext, LanguageProvider } from "@/app/LanguageContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
	currentLanguage,
}: Readonly<{
	children: React.ReactNode;
	currentLanguage?: string;
}>) {
	return (
		// <LanguageProvider>
		<html lang={currentLanguage || "en"}>
			<body className={inter.className}>
				{/* <Header /> */}
				{children}
				{/* <Footer /> */}
			</body>
		</html>
		// </LanguageProvider>
	);
}
